/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appelDjikstra */

#ifndef _Included_appelDjikstra
#define _Included_appelDjikstra
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     appelDjikstra
 * Method:    runDjikstra
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_appelDjikstra_runDjikstra
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
